### PR TITLE
MGDCTRS-1437: let google functions accept base64 service key

### PR DESCRIPTION
**Pull request by rinaldodev**
Use custom kamelet to let Google Functions receive the service account key as a base64, and add tests for Google Functions.

### CODE REVIEW

**Review by lburgazzoli — APPROVED** [review]
please backport/fix upstream

**Comment by rinaldodev** [comment]
> please backport/fix upstream

https://github.com/apache/camel-kamelets/pull/1109

**Review by lburgazzoli — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@oscerd @rinaldodev 
There is a "regen conflict" with https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/pull/474

**Comment by rinaldodev** [comment]
> @oscerd @rinaldodev There is a "regen conflict" with #474

You can merge the other one, the tests in here are still failing.

**Comment by oscerd** [comment]
Sorry for the incovenience. I merged the other one.

**Pull request merged**
