### PR TITLE
MGDCTRS-205 - Set default for CPU and Memory - Messaging Connectors

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by heiko-braun** [comment]
Thanks @oscerd

**Comment by heiko-braun** [comment]
Is this a good average?

```
"trait.camel.apache.org/container.request-cpu" : "0.20",
"trait.camel.apache.org/container.request-memory" : "256m",
```

**Comment by oscerd** [comment]
Yes, I discussed with @lburgazzoli for the CPU and also I'm looking at some test I'm doing for the memory side.

**Comment by oscerd** [comment]
Error is not related.

**Pull request merged**
