### PR TITLE
[MGDCTRS-1597]: Fix cos-kafka-source in Splunk and Ansible sink connectors

### PR DESCRIPTION
**Pull request by mkralik3**
ref.: https://issues.redhat.com/browse/MGDCTRS-1597

### CODE REVIEW

**Comment by rinaldodev** [comment]
Hi @mkralik3. Those json files are generated ones, so your changes would get overridden.
Those need to be changed in their pom.xml: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/blob/main/cos-fleet-catalog-connectors/itops/splunk-0.1/pom.xml#L44

**Comment by mkralik3** [comment]
@rinaldodev  oh, I see, thanks. Updated.

**Comment by rinaldodev** [comment]
I'll rebase my PR (https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/pull/445)
after merging this one, so you don't have to regenerate the catalog.

**Comment by mkralik3** [comment]
@rinaldodev Thanks

**Pull request merged**
